### ISSUE TITLE
Exception when loading module

### ISSUE THREAD

**Issue by Tierran** [Edubits/Zway-MQTT#3]
[2016-07-19 20:04:16.576] [I] [core] [MQTT_14] Error: Error: Message type error: 6
at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
at null._errorCallback (automation/userModules/MQTT/index.js:103:8)
at MQTTClient._onError (automation/userModules/MQTT/lib/mqtt.js:442:10)
at MQTTClient._onData (automation/userModules/MQTT/lib/mqtt.js:468:14)
at tcp.connection.onrecv (automation/userModules/MQTT/lib/mqtt.js:322:10)

**Comment by Edubits** [comment]
Thanks for reporting @Tierran. It seems the JS MQTT library I'm using doesn't handle a PUBREL (part of the QoS 2 protocol) well. You probably have a retained message with QoS 2 available. I will test this later, but something you might try as workaround is adding the following at line 208 of lib/mqtt.js:
`MQTTClient.messageHandlers[MQTTClient.PUBREL] = function (self, fixed_header, chunk) {};`

**Comment by Tierran** [comment]
Thanks for the quick response!  This also elicited an "Ah Ha!" moment.  I was testing my MQTT setup about a month ago and you're right on the money for the QoS 2 piece.  There is almost definitely a message hanging around in there which means I should just go clear out that queue.

But I guess it's good to have exposed this potential issue anyway. 8)

**Comment by Edubits** [comment]
In 1.3.1 I've added the empty message handler for PUBREL, it doesn't seem there are side effects of ignoring these messages. So now at least it doesn't add exceptions to the log.
