### ISSUE TITLE
MQTT error in zway log

### ISSUE THREAD

**Issue by antti365** [Edubits/Zway-MQTT#31]
Good afternoon,
Zway server - v2.3.7, mosquitto - v1.5., again a mistake in away logs:

[2018-06-17 18:57:42.284] [I] [core] [MQTT-68] Socket connection closed.
[2018-06-17 18:57:42.287] [I] [core] [MQTT_68] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:150:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:103:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:302:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:172:10)
[2018-06-17 18:57:42.308] [I] [core] [MQTT-68] Trying to reconnect (0)
[2018-06-17 18:57:42.318] [I] [core] [MQTT-68] Reconnect attempt finished
[2018-06-17 18:57:42.341] [I] [core] [MQTT-68] Socket connection opened.
[2018-06-17 18:57:42.341] [I] [core] [MQTT-68] Connected to 192.168.10.4 as Smarthome

in my opinion something similar already was, or am I mistaken? How can you get rid of this error? Thank you.

**Comment by ronie-z-wave** [comment]
Hi,

the same on my side:

[2018-06-20 08:08:10.484] [I] [zway] Removing job: Get background noise level
[2018-06-20 08:08:11.039] [I] [core] [MQTT-53] Trying to reconnect (6)
[2018-06-20 08:08:11.042] [I] [core] [MQTT-53] Reconnect attempt finished
[2018-06-20 08:08:11.063] [I] [core] [MQTT-53] Socket connection closed.
[2018-06-20 08:08:11.069] [I] [core] [MQTT_53] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:150:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:103:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:302:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:172:10)
[2018-06-20 08:08:18.088] [I] [core] [MQTT-53] Trying to reconnect (7)
[2018-06-20 08:08:18.091] [I] [core] [MQTT-53] Reconnect attempt finished
[2018-06-20 08:08:18.113] [I] [core] [MQTT-53] Socket connection closed.
[2018-06-20 08:08:18.118] [I] [core] [MQTT_53] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:150:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:103:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:302:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:172:10)

Seems also that this error leads in a z-way-server hang up or kill.
In z-way-server versions 2.3.7 and lower is a bug where the sockets won't be closed correctly. This will be fixed with this fix in next version https://github.com/Z-Wave-Me/home-automation/issues/473

Can you please have a look at it?

Thx in advance.

BR ronie

**Comment by antti365** [comment]
Thanks for the link, yes, it looks like the same error, you'll have to wait for the update ...

**Comment by kukachik** [comment]
Got this error too
```[2018-08-20 08:43:02.204] [I] [core] [MQTT-12] Reconnect attempt finished
[2018-08-20 08:43:02.227] [I] [core] [MQTT-12] Socket connection closed.
[2018-08-20 08:43:02.235] [I] [core] [MQTT_12] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:150:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:103:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:302:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:172:10)
```

Zway
Version number: | v2.3.7

**Comment by johnpdowling** [comment]
Using i8beef's latest pull and  z-way 2.3.8-rc6, this issue cleared up for me and I'm able to fully use the plugin with the MQTT server on my network.

**Comment by aivs** [comment]
on 2.3.8 MQTT can't start. Testet on Raspberry Pi and Popp hub
		//Application name
		'app_name': 'SmartHome UI',
		// Application version
		'app_version': '1.9.0',
		// Application (DIST) built date
		'app_built': '24-09-2018 14:06:32',
		// Application ID
		'app_id': 'SmartHomeUI',
<img width="1280" alt="2018-11-16 17 13 24" src="https://user-images.githubusercontent.com/2894860/48626662-88558280-e9c3-11e8-93a5-46cb12194a8a.png">

**Comment by MacAgent** [comment]
I'm on version z-way 3.1.1 / Base Module 1.11 / MQTT 1.4.1 and I keep getting this error too

[2020-12-16 10:43:30.039] [I] [core] [MQTT_5] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:173:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:110:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:303:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:173:10)
[2020-12-16 10:43:30.061] [I] [core] [MQTT-5] Trying to reconnect (0)
[2020-12-16 10:43:30.186] [I] [core] [MQTT-5] Reconnect attempt finished
[2020-12-16 10:43:30.209] [I] [core] [MQTT-5] Socket connection opened.
[2020-12-16 10:43:30.210] [I] [core] [MQTT-5] Connected to 192.168.42.247 as zway

Are there any settings which I could change?

regards

**Comment by MacAgent** [comment]
> I'm on version z-way 3.1.1 / Base Module 1.11 / MQTT 1.4.1 and I keep getting this error too
> 
> [2020-12-16 10:43:30.039] [I] [core] [MQTT_5] Error: Disconnected, will retry to connect...
> at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
> at MQTT.onDisconnect (automation/userModules/MQTT/index.js:173:7)
> at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:110:46)
> at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:303:10)
> at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:173:10)
> [2020-12-16 10:43:30.061] [I] [core] [MQTT-5] Trying to reconnect (0)
> [2020-12-16 10:43:30.186] [I] [core] [MQTT-5] Reconnect attempt finished
> [2020-12-16 10:43:30.209] [I] [core] [MQTT-5] Socket connection opened.
> [2020-12-16 10:43:30.210] [I] [core] [MQTT-5] Connected to 192.168.42.247 as zway
> 
> Are there any settings which I could change?
> 
> regards

For all those who are probably running into the same trouble as me (I searched for days). 
In my case it was related to the devices names which contains a hash sign (#) 

Solution found in issue #26 

have fun
