### ISSUE TITLE
Luminiscence and temperature error

### ISSUE THREAD

**Issue by ROYMartell** [Edubits/Zway-MQTT#40]
Using z-way 2.3.8 with latest MQTT app.
Config it with my mosquitto, everything work as expected with dimmers - states publishes to topic "smarthome/%roomName%/%deviceName%" for devices with specific tag. But when I try to add that tag to Philio Multi-Sensor for luminiscence or temperature, I've nothing in topics and error in log:

[2019-01-25 12:00:56.037] [I] [core] Notification: device-info (device-luminiscence): {"dev":"Luminiscence (#11)","l":"71 %","location":1}
[2019-01-25 12:00:56.103] [I] [core] [MQTT-15] Socket connection closed.
[2019-01-25 12:00:56.106] [I] [core] [MQTT_15] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:173:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:110:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:303:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:173:10)
[2019-01-25 12:00:56.107] [I] [core] [BaseModule-12] Set lastLevel to 71 for ZWayVDev_zway_11-0-49-3 (was 66)
[2019-01-25 12:00:56.163] [I] [core] [MQTT-15] Trying to reconnect (0)
[2019-01-25 12:00:56.165] [I] [core] [MQTT-15] Reconnect attempt finished
[2019-01-25 12:00:57.064] [I] [core] [MQTT-15] Socket connection opened.
[2019-01-25 12:00:57.065] [I] [core] [MQTT-15] Connected to localhost as zway

Am I doing something wrong or there is an error in module?

**Comment by ROYMartell** [comment]
Find out this was a naming problem. 
My device names have '#' by default, which led to an error
