### ISSUE TITLE
Cannot instantiate module: MQTT: 

### ISSUE THREAD

**Issue by tellblom** [Edubits/Zway-MQTT#5]
I get this error when trying to set up the config.

Any suggestion how to solve this?

[2016-08-02 20:18:47.626] [I] [core] --- Starting module Base Module
[2016-08-02 20:18:47.636] [I] [core] [BaseModule-10] Init callbacks
[2016-08-02 20:20:40.731] [I] [core] Notification: error (core): Cannot instantiate module: MQTT: TypeError: undefined is not a function
[2016-08-02 20:20:40.741] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:369:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:671:14)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1119:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)

**Comment by Edubits** [comment]
Hi @tellblom, thanks for the feedback! Which version of Zway are you using?

**Comment by tellblom** [comment]
Hi I use version  2.2.1 of Z-Way
