### ISSUE TITLE
Logs keeps spamming with errors

### ISSUE THREAD

**Issue by isMnemonic** [Edubits/Zway-MQTT#53]
I get my z-way log file spammed with:
`[2020-06-05 10:56:01.712] [I] [core] [MQTT-21] Socket connection opened.
[2020-06-05 10:56:01.712] [I] [core] [MQTT-21] Connected to mosquitto.compiler.se
[2020-06-05 10:56:01.713] [I] [core] [MQTT-21] ----------------- undefined
[2020-06-05 10:56:01.713] [I] [core] [MQTT-21] +++++++++++++++++ {"first_start_up":"2019-11-02T12:06:52.325Z","count_of_reconnects":40,"emailInitialActivated":true,"firstaccess":false}
[2020-06-05 10:56:02.726] [I] [core] [MQTT-21] Trying to reconnect (0)
[2020-06-05 10:56:03.750] [I] [core] [MQTT-21] Socket connection closed.
[2020-06-05 10:56:03.753] [I] [core] [MQTT_21] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:139:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:92:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:303:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:173:10)
[2020-06-05 10:56:03.753] [I] [core] [MQTT-21] Socket connection opened.
[2020-06-05 10:56:03.753] [I] [core] [MQTT-21] Connected to mosquitto.compiler.se
[2020-06-05 10:56:03.754] [I] [core] [MQTT-21] ----------------- undefined
[2020-06-05 10:56:03.754] [I] [core] [MQTT-21] +++++++++++++++++ {"first_start_up":"2019-11-02T12:06:52.325Z","count_of_reconnects":40,"emailInitialActivated":true,"firstaccess":false}
[2020-06-05 10:56:04.770] [I] [core] [MQTT-21] Trying to reconnect (0)
[2020-06-05 10:56:05.792] [I] [core] [MQTT-21] Socket connection closed.
[2020-06-05 10:56:05.797] [I] [core] [MQTT_21] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:139:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:92:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:303:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:173:10)
[2020-06-05 10:56:05.798] [I] [core] [MQTT-21] Socket connection opened.
[2020-06-05 10:56:05.798] [I] [core] [MQTT-21] Connected to mosquitto.compiler.se
[2020-06-05 10:56:05.798] [I] [core] [MQTT-21] ----------------- undefined
[2020-06-05 10:56:05.798] [I] [core] [MQTT-21] +++++++++++++++++ {"first_start_up":"2019-11-02T12:06:52.325Z","count_of_reconnects":40,"emailInitialActivated":true,"firstaccess":false}
[2020-06-05 10:56:06.812] [I] [core] [MQTT-21] Trying to reconnect (0)
[2020-06-05 10:56:07.835] [I] [core] [MQTT-21] Socket connection closed.
[2020-06-05 10:56:07.839] [I] [core] [MQTT_21] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at MQTT.onDisconnect (automation/userModules/MQTT/index.js:139:7)
    at MQTTClient._disconnectCallback (automation/userModules/MQTT/index.js:92:46)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:303:10)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:173:10)
[2020-06-05 10:56:07.840] [I] [core] [MQTT-21] Socket connection opened.
[2020-06-05 10:56:07.840] [I] [core] [MQTT-21] Connected to mosquitto.compiler.se
[2020-06-05 10:56:07.840] [I] [core] [MQTT-21] ----------------- undefined
[2020-06-05 10:56:07.841] [I] [core] [MQTT-21] +++++++++++++++++ {"first_start_up":"2019-11-02T12:06:52.325Z","count_of_reconnects":40,"emailInitialActivated":true,"firstaccess":false}
[2020-06-05 10:56:08.855] [I] [core] [MQTT-21] Trying to reconnect (0)
`

I  also gets a "%" inserted somehow into the topic and i do now know where to look and its only when the mqtt app in z-way is listening/sending.. I really dont know were to begin to look.

**Comment by isMnemonic** [comment]
I also find this in the mqtt broker log file:
`cc1591349679:   zway/# (QoS 0)
1591349679: zway 0 zway/#
1591349679: Sending SUBACK to zway
1591349679: Sending PUBLISH to zway (d0, q0, r1, m0, 'zway/dummyDevice/globalRoom/temperature', ... (2 bytes))
1591349679: Sending PUBLISH to zway (d0, q0, r1, m0, 'zway/livingroom/dht/temperature', ... (3 bytes))
1591349680: New connection from 192.168.1.19 on port 1883.
1591349680: Client zway already connected, closing old connection.
1591349680: New client connected from 192.168.1.19 as zway (p1, c0, k30, u'zwaymqtt').
1591349680: No will message specified.
1591349680: Sending CONNACK to zway (0, 0)
1591349681: Received SUBSCRIBE from zway
`

And that 3bytes should explain the "%" but where does it come from.. it only appears when i add a device in the mqtt app
